#!/usr/bin/env ruby

begin
  Object.const_get('Dailycrap')
rescue NameError
  require 'bundler/setup'
end

require 'dailycrap'
require 'date'
require 'trollop'
require 'tempfile'

opts = Trollop::options do
  banner <<-EOS
    Dailycrap is here to generate your daily meeting.
  EOS

  opt :token_file, "File containing your github token (https://github.com/settings/tokens)", required: true, type: :string
  opt :repository, "The repository you are working on", required: true, type: :string
  opt :organization, "Your organization name", default: nil, type: :string
  opt :day, "The day you want to generate a report for (default is yesterday or last friday if monday)", type: :string
  opt :edit, "Send generated report to your $EDITOR", default: false
end

crap = Dailycrap::Dailycrap.new(File.read(opts[:token_file]).strip,
                                date: opts[:day] ? Date.parse(opts[:day]) : (Date.today.monday? ? Date.today - 3 : Date.today - 1),
                                repo: opts[:repository],
                                organization: opts[:organization])

report = crap.daily
puts report

if opts[:edit]
  file = Tempfile.new('dailycrap')
  file.write(report)
  file.close
  pid = spawn("#{ENV['EDITOR']} #{file.path}")
  Process.wait(pid)
  file.unlink
end
